feat: Error checking and handling
Changes:
- Added function exit_on_error() to common/functions.
- Added error checking calls to exit_on_error() to instal scripts.

On branch develop
  Your branch is up to date with 'origin/develop'.

Changes to be committed:
  modified:   common/functions
  modified:   r_mariadb.sh
  modified:   r_nginx.sh
  modified:   v_svr_base.sh
  modified:   v_svr_base/v_svr_base_chroot.sh

diff --git a/common/functions b/common/functions
--- a/common/functions
+++ b/common/functions
@@ -1,8 +1,30 @@
+#!/bin/bash
+# enable !! command completion
+# - needed for exit_on_error
+set -o history -o histexpand
+
 #--------------------------------------------------------------------#
 # Common functions
 #--------------------------------------------------------------------#
 
-function is_valid_ipv4 ()
+# from https://intoli.com/blog/exit-on-errors-in-bash-scripts/
+# usage:
+#   <some command>
+#   exit_on_error $? $2
+#
+function exit_on_error()
+{
+	exit_code=$1
+	last_command=${@:2}
+	if [ $exit_code -ne 0 ]; then
+		>&2 echo -e "\e[0;31m\"${last_command}\" command failed with exit code ${exit_code}.\e[0m"
+		echo ''
+		exit $exit_code
+	fi
+}
+
+
+function is_valid_ipv4()
 {
 	#[[ "$1" =~ ^(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$ ]]
 
@@ -14,7 +36,7 @@ function is_valid_ipv4 ()
 	fi
 }
 
-function is_valid_ipv4_with_subnet_mask ()
+function is_valid_ipv4_with_subnet_mask()
 {
 	#[[ "$1" =~ ^(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)/([0-9]|[1-2][0-9]|3[0-2])$ ]]
 
